.gitignore, Makefile, main.py, pyproject.toml, requirements/dev.txt, src/cpg_flow/__init__.py, src/cpg_flow/hello_world.py
Setting up everything required to build the package using the pyproject.toml, build and twine.
I also included just a single functional file in cpg_flow called hello_world.py just to test the build functionality.
Currently pushing to testpypi.
This PR will allow us to setup our automated changelog and release system using semantic version. A future PR (if not included here) will be required to setup the package.yaml workflow for CI/CD in future.
=> Build setup

.github/workflows/package.yaml
=> fix(package.yaml): push to pypi not testpypi

.github/workflows/docker.yaml, .github/workflows/lint.yaml, .github/workflows/test.yaml
This uses the `production` environment in the workflow to package docker and also bumps `uv` versions in the other workflows.
=> Refactor Docker Workflow

src/cpg_flow/metamist.py, src/cpg_flow/stage.py, src/cpg_flow/status.py, src/cpg_flow/targets/cohort.py, src/cpg_flow/targets/multicohort.py
=> Pass Cohort IDs to create_analysis call to Metamist

src/cpg_flow/targets/cohort.py, src/cpg_flow/targets/dataset.py, src/cpg_flow/targets/multicohort.py, src/cpg_flow/targets/target.py, tests/test_workflow.py
Matches PR: https://github.com/populationgenomics/production-pipelines/pull/958/files
Solves: https://cpg-populationanalysis.atlassian.net/browse/SET-222?atlOrigin=eyJpIjoiNzFmZTRmYzU2ZjFjNDM5MWJiYTQ3OGYzZDIxYWY1YzgiLCJwIjoiaiJ9
=> Alignment inputs hash improvement

pyproject.toml, src/cpg_flow/inputs.py, src/cpg_flow/metamist.py, src/cpg_flow/stage.py, src/cpg_flow/targets/cohort.py, src/cpg_flow/targets/dataset.py, src/cpg_flow/targets/multicohort.py, src/cpg_flow/utils.py, src/cpg_flow/workflow.py, tests/__init__.py, tests/test_cohort.py, uv.lock
Liftover of this PR: https://github.com/populationgenomics/production-pipelines/pull/965
Resolves: https://cpg-populationanalysis.atlassian.net/jira/software/projects/SET/boards/4?assignee=712020:96514ed7-72b2-4817-9be5-947057e02a9c&issueParent=11082&selectedIssue=SET-242
=> Improved Logging

.github/workflows/test.yaml, .github/workflows/update-badges.yaml
So close! The workflow_run is working fine, but accessing outputs isn't. So switch to artifacts and see if that works.
=> Change to using artifacts

.github/workflows/update-badges.yaml
Not working for some reason. Trying to debug.
=> List downloaded artifacts

.github/workflows/update-badges.yaml
=> Update badges - use env variables correctly

.github/workflows/docker.yaml
Echo the pushed docker image that was built
=> ci(docker.yaml): echo out the docker tag

docs/badges.yaml, src/cpg_flow/inputs.py, tests/test_multicohort.py
Replicates the PR from prod pipes: https://github.com/populationgenomics/production-pipelines/pull/989
=> Set 361 force cohort ids to be unique

docs/badges.yaml, src/cpg_flow/inputs.py, tests/assets/test_multicohort/COH1.json, tests/assets/test_multicohort/COH2.json, tests/test_multicohort.py
https://github.com/populationgenomics/production-pipelines/pull/1068/files
=> fix: replicate prod pipes PR#1068

docs/badges.yaml, pyproject.toml, src/cpg_flow/metamist.py, src/cpg_flow/show_workflow/graph.py, src/cpg_flow/utils.py, src/cpg_flow/workflow.py, tests/test_cohort.py, uv.lock
migrating the PR from prod-pipes: https://github.com/populationgenomics/production-pipelines/pull/311
=> Display Workflow

.github/workflows/package.yaml, Makefile
The Package workflow is failing. Time to fix it.
=> Set 374 fix make ci build command in ci

src/cpg_flow/stage.py
Replicates https://github.com/populationgenomics/production-pipelines/pull/1124 
Related to https://github.com/populationgenomics/cpg-flow/issues/62 
Closes #62
=> fix(stage.py): as_str to take in path as well as str

tests/assets/test_cohort/pedigree.json, tests/assets/test_multicohort/pedigree.json, tests/test_cohort.py, tests/test_multicohort.py, uv.lock
Turns out we were most of the way there. I didn't move any in the `test_metamist.py` since they are using the api to make test cases and not just a dump of strings.
[SET-369](https://cpg-populationanalysis.atlassian.net/browse/SET-369)
[SET-369]: https://cpg-populationanalysis.atlassian.net/browse/SET-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Move all the test data into json files

.github/workflows/cleanup-sonarqube-project.yaml
Test the cleaup functionality for sonarqube.
=> Sonarqube test new setup

.github/workflows/cleanup-sonarqube-project.yaml
Try checking the project exists before attempting the delete.
=> ci(cleanup-sonarqube): check the project exists before the delete

.github/renovate-config.json, .markdownlint.json, .pre-commit-config.yaml, tests/assets/test_cohort/COH1.json, tests/assets/test_cohort/COH2.json, tests/assets/test_cohort/COH3.json, tests/assets/test_cohort/COH4.json, tests/assets/test_cohort/COH5.json, tests/assets/test_cohort/pedigree.json, tests/assets/test_multicohort/COH1.json, tests/assets/test_multicohort/COH123.json, tests/assets/test_multicohort/COH2.json, tests/assets/test_multicohort/COH456.json, tests/assets/test_multicohort/pedigree.json
What it says on the tin. Given we now have a fair few json files, it's worth adding the formatter to keep consistency.
=> Add json formatter to pre-commit hook

src/cpg_flow/workflow.py
Correction to previous correction - 
#99 wrongly edited the _MultiCohort_.analysis_dataset instead of the _Cohort_.analysis_dataset
This corrects (reverts) the previous change, and correctly edits the Cohort.analysis_dataset -> dataset
Solution for https://batch.hail.populationgenomics.org.au/batches/595001/jobs/1
=> fix(syntax): correction to previous correction

.github/workflows/package.yaml, .github/workflows/web-docs.yaml, .gitignore, Dockerfile, docs/docs/installation.md, pyproject.toml, src/cpg_flow/utils.py, uv.lock
The package step is still failling due to the error from the mike deploy docs step. This could be a possible solution.
=> Fix the mkdocs deploy

.commitlintrc.json, .pre-commit-config.yaml
The commitlint hook wasn't working correctly, this fixes it.
=> Fix commitlint hook

uv.lock
Addresses github.com/advisories/GHSA-9hjg-9r4m-mvj7
=> build: update requests package version

.github/sonarqube/sonarqube-fetch.sh, .github/sonarqube/sonarqube-template.md
Some new issues got pushed through to the main branch due to lack of visibility (that's why the main branch Quality Gate is currently failling).
This updates the SonarQube Summary to include new issues.
=> Sonarqube scan show new issues on both projects

uv.lock
Fixes: GHSA-48p4-8xcf-vxj5, GHSA-pq67-6m6q-mj2v
=> chore(deps): Bump urllib3
